name: Pull Request Build

on:
  # Run this on pushes to main, develop
  push:
    branches: [ main, develop ]

  # Run this on any pull request.
  pull_request:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Conan
      run: |
        pip install conan

    - name: Configure Conan
      run: |
        conan profile new ~/.conan2/profiles/default
        mkdir -p ~/.conan2/profiles
        cd ~/.conan2/profiles
        echo "[settings]" >> default
        echo "arch=x86_64" >> default
        echo "build_type=Release" >> default
        echo "compiler=clang" >> default
        echo "compiler.cppstd=gnu14" >> default
        echo "compiler.libcxx=libstdc++11" >> default
        echo "compiler.version=14" >> default
        echo "os=Linux" >> default

        conan profile show

    - name: Build
      run: |
        ./build-linux.sh
