name: Pull Request Build

on:
  # Run this on any pull request.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure Compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
        sudo update-alternatives --set cc /usr/bin/clang
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
        sudo update-alternatives --set c++ /usr/bin/clang++
        clang --version | grep -q 'clang version 14.0.0' && echo "Clang default version is as expected." || echo "Clang default version is changed on build runners. Please update generated conan-profiles/linux.profile, Dockerfile and pr-build.yml."

    - name: Install Conan
      run: |
        pip install conan

    - name: Build
      run: |
        ./build-linux.sh
