name: Pull Request Build

on:
  pull_request:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Conan
      run: |
        pip install conan

        # Detect profile(s)
        conan profile detect

    - name: Build
      run: |
        ./build-linux.sh
