name: Pull Request Build

on:
  # Run this on pushes to main, develop
  push:
    branches: [ main, develop ]

  # Run this on any pull request.
  pull_request:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Conan
      run: |
        pip install conan

    - name: Configure Conan
      run: |
        conan profile new ~/.conan2/profiles/default
        conan profile update settings.arch=x64 default
        conan profile update settings.build_type=Release default
        conan profile update settings.compiler.cppstd=gnu14 default
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile update settings.compiler.version=14 default
        conan profile update settings.os Linux default
        conan profile show

    - name: Build
      run: |
        ./build-linux.sh
